openapi: 3.0.3
info:
  title: Spotify Web API
  contact:
    name: sonallux
    url: https://github.com/sonallux/spotify-web-api
  version: 2021.10.17
servers:
- url: https://api.spotify.com/v1
tags:
- name: category-albums
  description: Albums API
- name: category-artists
  description: Artists API
- name: category-browse
  description: Browse API
- name: category-episodes
  description: Episodes API
- name: category-follow
  description: Follow API
- name: category-library
  description: Library API
- name: category-markets
  description: Markets API
- name: category-personalization
  description: Personalization API
- name: category-player
  description: Player API
- name: category-playlists
  description: Playlists API
- name: category-search
  description: Search API
- name: category-shows
  description: Shows API
- name: category-tracks
  description: Tracks API
- name: category-users-profile
  description: Users Profile API
paths:
  /albums/{id}:
    get:
      tags:
      - category-albums
      summary: Get an Album
      description: Get Spotify catalog information for a single album.
      operationId: get-an-album
      security:
      - oauth_2_0: []
  /albums/{id}/tracks:
    get:
      tags:
      - category-albums
      summary: Get an Album's Tracks
      description: |-
        Get Spotify catalog information about an album's tracks.
        Optional parameters can be used to limit the number of tracks returned.
      operationId: get-an-albums-tracks
      security:
      - oauth_2_0: []
  /albums:
    get:
      tags:
      - category-albums
      summary: Get Multiple Albums
      description: Get Spotify catalog information for multiple albums identified
        by their Spotify IDs.
      operationId: get-multiple-albums
      security:
      - oauth_2_0: []
  /artists/{id}:
    get:
      tags:
      - category-artists
      summary: Get an Artist
      description: Get Spotify catalog information for a single artist identified
        by their unique Spotify ID.
      operationId: get-an-artist
      security:
      - oauth_2_0: []
  /artists/{id}/albums:
    get:
      tags:
      - category-artists
      summary: Get an Artist's Albums
      description: Get Spotify catalog information about an artist's albums.
      operationId: get-an-artists-albums
      security:
      - oauth_2_0: []
  /artists/{id}/related-artists:
    get:
      tags:
      - category-artists
      summary: Get an Artist's Related Artists
      description: "Get Spotify catalog information about artists similar to a given\
        \ artist. Similarity is based on analysis of the Spotify community's [listening\
        \ history](http://news.spotify.com/se/2010/02/03/related-artists/)."
      operationId: get-an-artists-related-artists
      security:
      - oauth_2_0: []
  /artists/{id}/top-tracks:
    get:
      tags:
      - category-artists
      summary: Get an Artist's Top Tracks
      description: Get Spotify catalog information about an artist's top tracks by
        country.
      operationId: get-an-artists-top-tracks
      security:
      - oauth_2_0: []
  /artists:
    get:
      tags:
      - category-artists
      summary: Get Multiple Artists
      description: Get Spotify catalog information for several artists based on their
        Spotify IDs.
      operationId: get-multiple-artists
      security:
      - oauth_2_0: []
  /browse/categories/{category_id}/playlists:
    get:
      tags:
      - category-browse
      summary: Get a Category's Playlists
      description: Get a list of Spotify playlists tagged with a particular category.
      operationId: get-a-categories-playlists
      security:
      - oauth_2_0: []
  /browse/categories/{category_id}:
    get:
      tags:
      - category-browse
      summary: Get a Category
      description: "Get a single category used to tag items in Spotify (on, for example,\
        \ the Spotify player's \"Browse\" tab)."
      operationId: get-a-category
      security:
      - oauth_2_0: []
  /browse/categories:
    get:
      tags:
      - category-browse
      summary: Get All Categories
      description: "Get a list of categories used to tag items in Spotify (on, for\
        \ example, the Spotify player's \"Browse\" tab)."
      operationId: get-categories
      security:
      - oauth_2_0: []
  /browse/featured-playlists:
    get:
      tags:
      - category-browse
      summary: Get All Featured Playlists
      description: "Get a list of Spotify featured playlists (shown, for example,\
        \ on a Spotify player's 'Browse' tab)."
      operationId: get-featured-playlists
      security:
      - oauth_2_0: []
  /browse/new-releases:
    get:
      tags:
      - category-browse
      summary: Get All New Releases
      description: "Get a list of new album releases featured in Spotify (shown, for\
        \ example, on a Spotify player's \"Browse\" tab)."
      operationId: get-new-releases
      security:
      - oauth_2_0: []
  /recommendations/available-genre-seeds:
    get:
      tags:
      - category-browse
      summary: Get Recommendation Genres
      description: "Retrieve a list of available genres seed parameter values for\
        \ [recommendations](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-recommendations)."
      operationId: get-recommendation-genres
      security:
      - oauth_2_0: []
  /recommendations:
    get:
      tags:
      - category-browse
      summary: Get Recommendations
      description: "Recommendations are generated based on the available information\
        \ for a given seed entity and matched against similar artists and tracks.\
        \ If there is sufficient information about the provided seeds, a list of tracks\
        \ will be returned together with pool size details."
      operationId: get-recommendations
      security:
      - oauth_2_0: []
  /episodes/{id}:
    get:
      tags:
      - category-episodes
      summary: Get an Episode
      description: |-
        Get Spotify catalog information for a single episode identified by its
        unique Spotify ID.
      operationId: get-an-episode
      security:
      - oauth_2_0:
        - user-read-playback-position
  /episodes:
    get:
      tags:
      - category-episodes
      summary: Get Multiple Episodes
      description: Get Spotify catalog information for several episodes based on their
        Spotify IDs.
      operationId: get-multiple-episodes
      security:
      - oauth_2_0:
        - user-read-playback-position
  /me/following/contains:
    get:
      tags:
      - category-follow
      summary: Get Following State for Artists/Users
      description: Check to see if the current user is following one or more artists
        or other Spotify users.
      operationId: check-current-user-follows
      security:
      - oauth_2_0:
        - user-follow-read
  /playlists/{playlist_id}/followers/contains:
    get:
      tags:
      - category-follow
      summary: Check if Users Follow a Playlist
      description: Check to see if one or more Spotify users are following a specified
        playlist.
      operationId: check-if-user-follows-playlist
      security:
      - oauth_2_0:
        - playlist-read-private
  /me/following:
    get:
      tags:
      - category-follow
      summary: Get User's Followed Artists
      description: Get the current user's followed artists.
      operationId: get-followed
      security:
      - oauth_2_0:
        - user-follow-read
    put:
      tags:
      - category-follow
      summary: Follow Artists or Users
      description: Add the current user as a follower of one or more artists or other
        Spotify users.
      operationId: follow-artists-users
      security:
      - oauth_2_0:
        - user-follow-modify
    delete:
      tags:
      - category-follow
      summary: Unfollow Artists or Users
      description: Remove the current user as a follower of one or more artists or
        other Spotify users.
      operationId: unfollow-artists-users
      security:
      - oauth_2_0:
        - user-follow-modify
  /playlists/{playlist_id}/followers:
    put:
      tags:
      - category-follow
      summary: Follow a Playlist
      description: Add the current user as a follower of a playlist.
      operationId: follow-playlist
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
    delete:
      tags:
      - category-follow
      summary: Unfollow Playlist
      description: Remove the current user as a follower of a playlist.
      operationId: unfollow-playlist
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
  /me/albums/contains:
    get:
      tags:
      - category-library
      summary: Check User's Saved Albums
      description: Check if one or more albums is already saved in the current Spotify
        user's 'Your Music' library.
      operationId: check-users-saved-albums
      security:
      - oauth_2_0:
        - user-library-read
  /me/episodes/contains:
    get:
      tags:
      - category-library
      summary: Check User's Saved Episodes
      description: "Check if one or more episodes is already saved in the current\
        \ Spotify user's 'Your Episodes' library.  \n\nThis API endpoint is in **beta**\
        \ and could change without warning. Please share any feedback that you have,\
        \ or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).."
      operationId: check-users-saved-episodes
      security:
      - oauth_2_0:
        - user-library-read
  /me/shows/contains:
    get:
      tags:
      - category-library
      summary: Check User's Saved Shows
      description: Check if one or more shows is already saved in the current Spotify
        user's library.
      operationId: check-users-saved-shows
      security:
      - oauth_2_0:
        - user-library-read
  /me/tracks/contains:
    get:
      tags:
      - category-library
      summary: Check User's Saved Tracks
      description: Check if one or more tracks is already saved in the current Spotify
        user's 'Your Music' library.
      operationId: check-users-saved-tracks
      security:
      - oauth_2_0:
        - user-library-read
  /me/albums:
    get:
      tags:
      - category-library
      summary: Get User's Saved Albums
      description: Get a list of the albums saved in the current Spotify user's 'Your
        Music' library.
      operationId: get-users-saved-albums
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - category-library
      summary: Save Albums for Current User
      description: Save one or more albums to the current user's 'Your Music' library.
      operationId: save-albums-user
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - category-library
      summary: Remove Albums for Current User
      description: Remove one or more albums from the current user's 'Your Music'
        library.
      operationId: remove-albums-user
      security:
      - oauth_2_0:
        - user-library-modify
  /me/episodes:
    get:
      tags:
      - category-library
      summary: Get User's Saved Episodes
      description: "Get a list of the episodes saved in the current Spotify user's\
        \ library.  \n\nThis API endpoint is in **beta** and could change without\
        \ warning. Please share any feedback that you have, or issues that you discover,\
        \ in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)."
      operationId: get-users-saved-episodes
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - category-library
      summary: Save Episodes for User
      description: "Save one or more episodes to the current user's library.  \n\n\
        This API endpoint is in **beta** and could change without warning. Please\
        \ share any feedback that you have, or issues that you discover, in our [developer\
        \ community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)."
      operationId: save-episodes-user
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - category-library
      summary: Remove User's Saved Episodes
      description: "Remove one or more episodes from the current user's library. \
        \ \n\nThis API endpoint is in **beta** and could change without warning. Please\
        \ share any feedback that you have, or issues that you discover, in our [developer\
        \ community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)."
      operationId: remove-episodes-user
      security:
      - oauth_2_0:
        - user-library-modify
  /me/shows:
    get:
      tags:
      - category-library
      summary: Get User's Saved Shows
      description: Get a list of shows saved in the current Spotify user's library.
        Optional parameters can be used to limit the number of shows returned.
      operationId: get-users-saved-shows
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - category-library
      summary: Save Shows for Current User
      description: Save one or more shows to current Spotify user's library.
      operationId: save-shows-user
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - category-library
      summary: Remove User's Saved Shows
      description: Delete one or more shows from current Spotify user's library.
      operationId: remove-shows-user
      security:
      - oauth_2_0:
        - user-library-modify
  /me/tracks:
    get:
      tags:
      - category-library
      summary: Get User's Saved Tracks
      description: Get a list of the songs saved in the current Spotify user's 'Your
        Music' library.
      operationId: get-users-saved-tracks
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - category-library
      summary: Save Tracks for User
      description: Save one or more tracks to the current user's 'Your Music' library.
      operationId: save-tracks-user
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - category-library
      summary: Remove User's Saved Tracks
      description: Remove one or more tracks from the current user's 'Your Music'
        library.
      operationId: remove-tracks-user
      security:
      - oauth_2_0:
        - user-library-modify
  /markets:
    get:
      tags:
      - category-markets
      summary: Get Available Markets
      description: Get the list of markets where Spotify is available.
      operationId: get-available-markets
      security:
      - oauth_2_0: []
  /me/top/{type}:
    get:
      tags:
      - category-personalization
      summary: Get a User's Top Artists and Tracks
      description: Get the current user's top artists or tracks based on calculated
        affinity.
      operationId: get-users-top-artists-and-tracks
      security:
      - oauth_2_0:
        - user-top-read
  /me/player/queue:
    post:
      tags:
      - category-player
      summary: Add an item to queue
      description: Add an item to the end of the user's current playback queue.
      operationId: add-to-queue
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/devices:
    get:
      tags:
      - category-player
      summary: Get a User's Available Devices
      description: Get information about a user's available devices.
      operationId: get-a-users-available-devices
      security:
      - oauth_2_0:
        - user-read-playback-state
  /me/player:
    get:
      tags:
      - category-player
      summary: Get Information About The User's Current Playback
      description: "Get information about the user's current playback state, including\
        \ track or episode, progress, and active device."
      operationId: get-information-about-the-users-current-playback
      security:
      - oauth_2_0:
        - user-read-playback-state
    put:
      tags:
      - category-player
      summary: Transfer a User's Playback
      description: Transfer playback to a new device and determine if it should start
        playing.
      operationId: transfer-a-users-playback
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/recently-played:
    get:
      tags:
      - category-player
      summary: Get Current User's Recently Played Tracks
      description: |-
        Get tracks from the current user's recently played tracks.
        ***Note**: Currently doesn't support podcast episodes.*
      operationId: get-recently-played
      security:
      - oauth_2_0:
        - user-read-recently-played
  /me/player/currently-playing:
    get:
      tags:
      - category-player
      summary: Get the User's Currently Playing Track
      description: Get the object currently being played on the user's Spotify account.
      operationId: get-the-users-currently-playing-track
      security:
      - oauth_2_0:
        - user-read-currently-playing
  /me/player/pause:
    put:
      tags:
      - category-player
      summary: Pause a User's Playback
      description: Pause playback on the user's account.
      operationId: pause-a-users-playback
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/seek:
    put:
      tags:
      - category-player
      summary: Seek To Position In Currently Playing Track
      description: Seeks to the given position in the user's currently playing track.
      operationId: seek-to-position-in-currently-playing-track
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/repeat:
    put:
      tags:
      - category-player
      summary: Set Repeat Mode On User’s Playback
      description: |-
        Set the repeat mode for the user's playback. Options are repeat-track,
        repeat-context, and off.
      operationId: set-repeat-mode-on-users-playback
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/volume:
    put:
      tags:
      - category-player
      summary: Set Volume For User's Playback
      description: Set the volume for the user's current playback device.
      operationId: set-volume-for-users-playback
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/next:
    post:
      tags:
      - category-player
      summary: Skip User’s Playback To Next Track
      description: Skips to next track in the user's queue.
      operationId: skip-users-playback-to-next-track
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/previous:
    post:
      tags:
      - category-player
      summary: Skip User’s Playback To Previous Track
      description: Skips to previous track in the user's queue.
      operationId: skip-users-playback-to-previous-track
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/play:
    put:
      tags:
      - category-player
      summary: Start/Resume a User's Playback
      description: Start a new context or resume current playback on the user's active
        device.
      operationId: start-a-users-playback
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/shuffle:
    put:
      tags:
      - category-player
      summary: Toggle Shuffle For User’s Playback
      description: Toggle shuffle on or off for user's playback.
      operationId: toggle-shuffle-for-users-playback
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /playlists/{playlist_id}/tracks:
    get:
      tags:
      - category-playlists
      summary: Get a Playlist's Items
      description: Get full details of the items of a playlist owned by a Spotify
        user.
      operationId: get-playlists-tracks
      security:
      - oauth_2_0: []
    put:
      tags:
      - category-playlists
      summary: Reorder or Replace a Playlist's Items
      description: |-
        Either reorder or replace items in a playlist depending on the request's parameters.
        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.
        To replace items, include `uris` as either a query parameter or in the request's body.
        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.


        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.
        These operations can't be applied together in a single request.
      operationId: reorder-or-replace-playlists-tracks
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
    post:
      tags:
      - category-playlists
      summary: Add Items to a Playlist
      description: Add one or more items to a user's playlist.
      operationId: add-tracks-to-playlist
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
    delete:
      tags:
      - category-playlists
      summary: Remove Items from a Playlist
      description: Remove one or more items from a user's playlist.
      operationId: remove-tracks-playlist
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
  /playlists/{playlist_id}:
    get:
      tags:
      - category-playlists
      summary: Get a Playlist
      description: Get a playlist owned by a Spotify user.
      operationId: get-playlist
      security:
      - oauth_2_0: []
    put:
      tags:
      - category-playlists
      summary: Change a Playlist's Details
      description: |-
        Change a playlist's name and public/private state. (The user must, of
        course, own the playlist.)
      operationId: change-playlist-details
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
  /users/{user_id}/playlists:
    get:
      tags:
      - category-playlists
      summary: Get a List of a User's Playlists
      description: Get a list of the playlists owned or followed by a Spotify user.
      operationId: get-list-users-playlists
      security:
      - oauth_2_0:
        - playlist-read-collaborative
        - playlist-read-private
    post:
      tags:
      - category-playlists
      summary: Create a Playlist
      description: |-
        Create a playlist for a Spotify user. (The playlist will be empty until
        you [add tracks](https://developer.spotify.com/documentation/web-api/reference/#endpoint-add-tracks-to-playlist).)
      operationId: create-playlist
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
  /me/playlists:
    get:
      tags:
      - category-playlists
      summary: Get a List of Current User's Playlists
      description: |-
        Get a list of the playlists owned or followed by the current Spotify
        user.
      operationId: get-a-list-of-current-users-playlists
      security:
      - oauth_2_0:
        - playlist-read-collaborative
        - playlist-read-private
  /playlists/{playlist_id}/images:
    get:
      tags:
      - category-playlists
      summary: Get a Playlist Cover Image
      description: Get the current image associated with a specific playlist.
      operationId: get-playlist-cover
      security:
      - oauth_2_0: []
    put:
      tags:
      - category-playlists
      summary: Upload a Custom Playlist Cover Image
      description: Replace the image used to represent a specific playlist.
      operationId: upload-custom-playlist-cover
      security:
      - oauth_2_0:
        - playlist-modify-private
        - playlist-modify-public
        - ugc-image-upload
  /search:
    get:
      tags:
      - category-search
      summary: Search for an Item
      description: |-
        Get Spotify Catalog information about albums, artists, playlists, tracks, shows or episodes
        that match a keyword string.
      operationId: search
      security:
      - oauth_2_0:
        - user-read-private
  /shows/{id}:
    get:
      tags:
      - category-shows
      summary: Get a Show
      description: |-
        Get Spotify catalog information for a single show identified by its
        unique Spotify ID.
      operationId: get-a-show
      security:
      - oauth_2_0:
        - user-read-playback-position
  /shows/{id}/episodes:
    get:
      tags:
      - category-shows
      summary: Get a Show's Episodes
      description: Get Spotify catalog information about an show's episodes. Optional
        parameters can be used to limit the number of episodes returned.
      operationId: get-a-shows-episodes
      security:
      - oauth_2_0:
        - user-read-playback-position
  /shows:
    get:
      tags:
      - category-shows
      summary: Get Multiple Shows
      description: Get Spotify catalog information for several shows based on their
        Spotify IDs.
      operationId: get-multiple-shows
      security:
      - oauth_2_0:
        - user-read-playback-position
  /audio-analysis/{id}:
    get:
      tags:
      - category-tracks
      summary: Get Audio Analysis for a Track
      description: |-
        Get a detailed audio analysis for a single track identified by its unique
        Spotify ID.
      operationId: get-audio-analysis
      security:
      - oauth_2_0: []
  /audio-features/{id}:
    get:
      tags:
      - category-tracks
      summary: Get Audio Features for a Track
      description: |-
        Get audio feature information for a single track identified by its unique
        Spotify ID.
      operationId: get-audio-features
      security:
      - oauth_2_0: []
  /audio-features:
    get:
      tags:
      - category-tracks
      summary: Get Audio Features for Several Tracks
      description: Get audio features for multiple tracks based on their Spotify IDs.
      operationId: get-several-audio-features
      security:
      - oauth_2_0: []
  /tracks:
    get:
      tags:
      - category-tracks
      summary: Get Several Tracks
      description: Get Spotify catalog information for multiple tracks based on their
        Spotify IDs.
      operationId: get-several-tracks
      security:
      - oauth_2_0: []
  /tracks/{id}:
    get:
      tags:
      - category-tracks
      summary: Get a Track
      description: |-
        Get Spotify catalog information for a single track identified by its
        unique Spotify ID.
      operationId: get-track
      security:
      - oauth_2_0: []
  /me:
    get:
      tags:
      - category-users-profile
      summary: Get Current User's Profile
      description: |-
        Get detailed profile information about the current user (including the
        current user's username).
      operationId: get-current-users-profile
      security:
      - oauth_2_0:
        - user-read-email
        - user-read-private
  /users/{user_id}:
    get:
      tags:
      - category-users-profile
      summary: Get a User's Profile
      description: Get public profile information about a Spotify user.
      operationId: get-users-profile
      security:
      - oauth_2_0: []
components:
  securitySchemes:
    oauth_2_0:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            playlist-read-private: Read access to user's private playlists.
            playlist-read-collaborative: Include collaborative playlists when requesting
              a user's playlists.
            ugc-image-upload: Write access to user-provided images.
            user-follow-read: Read access to the list of artists and other users that
              the user follows.
            playlist-modify-private: Write access to a user's private playlists.
            user-read-email: Read access to user’s email address.
            user-read-private: Read access to user’s subscription details (type of
              user account).
            app-remote-control: Remote control playback of Spotify. This scope is
              currently available to Spotify iOS and Android SDKs.
            streaming: Control playback of a Spotify track. This scope is currently
              available to the Web Playback SDK. The user must have a Spotify Premium
              account.
            user-follow-modify: Write/delete access to the list of artists and other
              users that the user follows.
            user-modify-playback-state: Write access to a user’s playback state
            user-library-read: Read access to a user's library.
            user-library-modify: Write/delete access to a user's "Your Music" library.
            playlist-modify-public: Write access to a user's public playlists.
            user-read-playback-state: Read access to a user’s player state.
            user-read-currently-playing: Read access to a user’s currently playing
              content.
            user-read-recently-played: Read access to a user’s recently played tracks.
            user-read-playback-position: Read access to a user’s playback position
              in a content.
            user-top-read: Read access to a user's top artists and tracks.
