name: Release
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: Create version string
        run: |
          new_version=$(date +"%Y.%-m.%-d")
          echo "Releasing version $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV
      - name: Use version
        run: |
          echo "Version ${{ env.new_version }}"
      - name: Print all tags
        run: |
          git tag
