name: Release
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  create-version:
    name: Create version string
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.create-version.outputs.new-version }}
    steps:
      - name: Create version string
        id: create-version
        run: |
          new_version=$(date +"%Y.%-m.%-d")
          echo "Releasing version $new_version"
          echo "::set-output name=new_version::$new_version"
      - name: Use version
        run: |
          echo "Version ${{ steps.create-version.outputs.new-version }}"
  check-version:
    name: Check Version
    needs: create-version
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: |
          echo "Version ${{ needs.create-version.outputs.new-version }}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We want all history so we can get all tags since previous git tag
      - name: Print all tags
        run: |
          git tag
